name: String-Analyser CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #Gets the react code
      - uses: actions/setup-node@v1 #Sets up node environment
        with:
          node-version: 16
      - run: npm ci #Installs dependencies
        env:
          CI: true
      - run: npm run build #Runs the build script
      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0 #Action for pushing build to netlify
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: "./build"
          comment-on-commit: true #The comment should contain deployment url

